// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPO5SL2Qdoi0kVXgyQnCoWuAdbUfh_YAo',
    appId: '1:607527844560:web:2415525d9fa986fdc03cd5',
    messagingSenderId: '607527844560',
    projectId: 'dashboard-baf3f',
    authDomain: 'dashboard-baf3f.firebaseapp.com',
    storageBucket: 'dashboard-baf3f.firebasestorage.app',
    measurementId: 'G-5CN9G1FZ0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSTYBgXETTOIN9r4XhiBP08051TCGlls8',
    appId: '1:607527844560:android:494f19173006ff81c03cd5',
    messagingSenderId: '607527844560',
    projectId: 'dashboard-baf3f',
    storageBucket: 'dashboard-baf3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL2BT2-MYBcv4FwRjXdBxYYGJk2ZCkQPo',
    appId: '1:607527844560:ios:348e02e0ccfe5bc8c03cd5',
    messagingSenderId: '607527844560',
    projectId: 'dashboard-baf3f',
    storageBucket: 'dashboard-baf3f.firebasestorage.app',
    iosBundleId: 'com.cervus.dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL2BT2-MYBcv4FwRjXdBxYYGJk2ZCkQPo',
    appId: '1:607527844560:ios:348e02e0ccfe5bc8c03cd5',
    messagingSenderId: '607527844560',
    projectId: 'dashboard-baf3f',
    storageBucket: 'dashboard-baf3f.firebasestorage.app',
    iosBundleId: 'com.cervus.dashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPO5SL2Qdoi0kVXgyQnCoWuAdbUfh_YAo',
    appId: '1:607527844560:web:8b119cf84e412423c03cd5',
    messagingSenderId: '607527844560',
    projectId: 'dashboard-baf3f',
    authDomain: 'dashboard-baf3f.firebaseapp.com',
    storageBucket: 'dashboard-baf3f.firebasestorage.app',
    measurementId: 'G-XJDWK0ZJR1',
  );
}
